### ISSUE TITLE
 Fresh Plugin of Bazarr fails on install

### ISSUE THREAD

**Issue by pavak1** [ix-plugin-hub/iocage-plugin-index#230]
error given on creation
"  bazarr had a failure Exception: RuntimeError Message: pkg error: - py37-pip :,py37-libxml2 : Refusing to fetch artifact and run post_install.sh! Partial plugin destroyed"

it appears that the plugin try's to install py37 vs py38 and py37 is unavailable

**Comment by fulder** [comment]
@pavak1 thanks for the issue, good finding and timing. I was just looking through some of the plugins with old python 3.7 dependencies yesterday and created a PR for all missing plugins (without any open PR already): https://github.com/ix-plugin-hub/iocage-plugin-index/pull/232

I've also updated the bazarr plugin with more generic `python3` references, it has been merged and ported back to the 12.2 release branch: 
* https://github.com/fulder/iocage-plugin-bazarr/pull/6
* https://github.com/fulder/iocage-plugin-bazarr/pull/7

After these fixes the cirrus tests seemed to pass on my fork (see: https://cirrus-ci.com/task/6672071733280768) so should probably pass in this repo PR as well soon.

**Comment by pavak1** [comment]
@fulder Thank you for looking into the problem and doing the work! It appears that the changes where blocked for merging issue #232, but probably just needs a review.

**Comment by fulder** [comment]
@pavak1, I've pushed a small fix after a comment to the PR, but otherwise it's just waiting for approval and merge now :) 

As a side note it would be nice to capture these package issues faster and in a more automated manner (see: https://github.com/ix-plugin-hub/iocage-plugin-index/issues/194)

**Comment by achmetinternet** [comment]
I installed the plugin and can SSH into the jail but the UI doesn't work, I get 

Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by fulder** [comment]
@achmetinternet (this should maybe be another issue than this close one but answering here anyways) it looks like bazarr plugin has changed a few things how it is installed and updated. The Internal Server Errors you are seeing are probably because there are some assets files missing while just cloning the repo. I've merged and backproted some fixes (and quickfixes) which should make a current bazarr installation upgrade and a clean update of the plugin work better (I hope).

Could you test once again on your side if it works better or if there are some more issues with this plugin? Thank you for your help and information about this.
